### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by patrafter1999** [huku-/pyxed#1]
Thanks for putting this together. It's awesome.

I'm trying to use it in Windows, but makefile is configured for linux only. I'm not a python or makefile expert. Could you set up makefile for Windows as well?

Thanks.

**Comment by huku-** [comment]
Hey there,

Give me some time to prepare Makefiles for both Dev-Cpp/MinGW and Visual Studio and run some tests. I'll push the changes as soon as possible.

**Comment by huku-** [comment]
Looks like XED libraries cannot be linked by ld.exe of Dev-Cpp/MinGW. Nevertheless, I have created a Makefile for Microsoft's nmake which builds pyxed successfully under Windows (nmake comes with Visual Studio; I use VS2010).

I'm currently doing some modifications in the code to avoid compiler warnings and will soon push the changes.

**Comment by huku-** [comment]
I have pushed the changes. To build pyxed under Windows:
- Open a command prompt
- Run **C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat** (or the corresponding batch file for your version of VS)
- Enter pyxed's top level directory
- Edit the values of **PYTHON27_PREFIX** and **XED_PREFIX** in **Makefile.nmake**
- Run **nmake -f Makefile.nmake**
- Test by using **set PYTHONPATH=.** followed by **python examples/written_regs.py 41414141**

If the compiler throws any warnings/errors please mail them to me :)

I will soon update the README and upload a precompiled release somewhere.

**Comment by huku-** [comment]
Experimental precompiled binary for 32 bits (includes debug symbols):

https://www.grhack.net/pyxed-x86.zip
