### ISSUE TITLE
Consider building XED statically

### ISSUE THREAD

**Issue by woodruffw** [huku-/pyxed#10]
Have you considered linking `pyxed` against a static build of XED?

Doing so would make usage slightly easier on macOS and would probably make it easier to eventually publish `pyxed` distributions to PyPI (if desired).

Experimentally, I was able to change `--shared` to `--static` in `setup.py` and use the resultant `pyxed` build without any problems. I'd be happy to make a PR for the changeset, if desired.

**Comment by huku-** [comment]
I remember playing with shared and static linking in the past, but I don't remember why I picked the one over the other. If `--static` works fine, then feel free to submit a PR. Thanks!

**Comment by woodruffw** [comment]
Alright, I opened up #11 with the changes needed to replace the shared build with a static one.

I'm also going to open a PR shortly to add a few unit tests, since these I've been making changes that affect the link interface and could manifest at runtime as missing symbol errors. Having some tests in the CI should eliminate that possibility, so I suggest merging the tests first 🙂
