### ISSUE TITLE
setup.py: Allow pre-built XED

### ISSUE THREAD

**Issue by langston-barrett** [huku-/pyxed#14]
I'd like to build this package with Nix. This would be easiest if the build allowed for pre-built XED (which seems to be the case with the Makefile, by overriding variables, but not with `setup.py`, which hardcodes them). Perhaps if `XED_CURRENT_KIT_DIR` is set in the environment, skip trying to build it?

**Comment by huku-** [comment]
Sure, why not. I have already merged your changes. Thank you very much for contributing!
