### ISSUE TITLE
macOS 10.13 build

### ISSUE THREAD

**Issue by andermoran** [huku-/pyxed#2]
When running make
`rm -fr *.pyc
cc -fPIC -O2 -I/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/pin-2.14-71313-clang.5.1-mac/extras/xed-intel64/include -Wall -Wextra -Wno-unknown-warning -Wno-unknown-warning-option -Wno-unused-parameter -Wno-old-style-declaration -Wno-strict-aliasing -ggdb   -c -o check.o check.c
In file included from check.c:6:
./includes.h:11:10: fatal error: 'xed-interface.h' file not found
#include "xed-interface.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [check.o] Error 1
`
macOS 10.13
XED_PREFIX=pin-2.14-71313-clang.5.1-mac/extras/xed-intel64

**Comment by andermoran** [comment]
I believe this requires pin tools to be already installed on the system which I don't have

**Comment by andermoran** [comment]
The `/` in front of `pin-2.14-71313-clang.5.1-mac/extras/xed-intel64/include` was added by me. It still fails even if it looks like `-Ipin-2.14-71313-clang.5.1-mac/extras/xed-intel64/include`

**Comment by andermoran** [comment]
Fixed it.
Download [Pin 3.6](https://software.intel.com/en-us/articles/pin-a-binary-instrumentation-tool-downloads). Untar the download and mov the directory to the main directory of pyxed. Set `XED_PREFIX=pin-3.6-97554-g31f0a167d-clang-mac/extras/xed-intel64` in the makefile.

**Comment by andermoran** [comment]
Also set `XED_HEADERS=$(XED_PREFIX)/include/xed`

**Comment by huku-** [comment]
Hello,

Sorry for the delayed reply. As you have pointed out, you need to set **XED\_PREFIX** to the appropriate path before compiling **pyxed**. This is also mentioned in the project's **README.md**. The problem with **XED\_HEADERS** pops up because in recent versions of Intel's XED, the path to the C headers has changed a bit. I will try to run some tests with a newer version of XED and will commit any changes.

**Comment by huku-** [comment]
Modified **Makefile** to use the correct **XED\_HEADERS** path (https://github.com/huku-/pyxed/commit/0266d520e7b18b5c2c5943b5f4e1143058634f7a).
