### ISSUE TITLE
Python 3 build fails on Ubuntu

### ISSUE THREAD

**Issue by andreas-abel** [huku-/pyxed#20]
On Ubuntu 20.04 (Python 3.8.10), when I run the following commands:

```
git clone https://github.com/huku-/pyxed.git
cd pyxed/
git submodule update --init --recursive
python3 setup.py build
```
I get the following error:
```
external/xed/mfile.py
Xed directory not initialized, run:
git submodule update --init --recursive
```
The `external/xed/mfile.py` file exists on my system.

**Comment by simsudo** [comment]
@andreas-abel did you find a solution?

**Comment by huku-** [comment]
Hello,

Apologies for my late reply, unfortunately I have kind of abandoned **pyxed** development.

I just pushed a few changes (including extended **setup.py** modifications) and have tested that everything works on both Python 2.x and 3.x.
