### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by mullick1998** [huku-/pyxed#21]
hello, 
I tried to built with python3 as well as python2 and got errors for both.
While building with python3 I got this error:
```
external/xed/mfile.py
Xed directory not initialized, run:
git submodule update --init --recursive
```
Although I already got the submodule before building

While building with python2, this was the error I got:
```
rm -fr *.pyc
cc -fPIC -O2 -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -Ixed-install-base-2018-07-05-mac-x86-64/include/xed -Wall -Wextra -Wno-unknown-warning -Wno-unknown-warning-option -Wno-unused-parameter -Wno-old-style-declaration -Wno-strict-aliasing -ggdb   -c -o check.o check.c
In file included from check.c:6:
includes.h:11:10: fatal error: xed-interface.h: No such file or directory
   11 | #include "xed-interface.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: check.o] Error 1
```

I checked some earlier issues regarding the `xed-interface.h`, and got the linux pin and also implemented as suggested [here](https://github.com/huku-/pyxed/issues/2). but it also didn't work. 

What could be the possible solution for that?

**Comment by huku-** [comment]
Hello,

Apologies for my late reply, unfortunately I have kind of abandoned **pyxed** development.

I just pushed a few changes and have tested that everything works on both Python 2.x and 3.x.

Please have a look at the updated README. The build process is now based purely on `setuptools`.
