### ISSUE TITLE
Fail to import XED_REG_ST objects to Python

### ISSUE THREAD

**Issue by majinxx297** [huku-/pyxed#3]
Python cannot find XED_REG_ST0 through XED_REG_ST7 when I try to use those objects.
That's because the following line will get name st(0) instead of ST0, while XED_REG_st(0) is not a valid object name (Correct me if i'm wrong.)
https://github.com/huku-/pyxed/blob/a68d73b797237c8cfee32349bac34c09db39817d/pyxed.c#L160
I have fixed this problem on my local copy, and here is the patch.
https://gist.github.com/majinxx297/39b9b6fd5ebcb75a49b63acb41958555
Feel free to use it if you want.

**Comment by huku-** [comment]
Thanks for reporting. I have pushed the relevant changes (https://github.com/huku-/pyxed/commit/0266d520e7b18b5c2c5943b5f4e1143058634f7a).
